### ISSUE TITLE
Overflow error is not reported

### ISSUE THREAD

**Issue by giniedp** [asifjalil/cli#10]
I came across a situation where an overflow error is not reported when executing a statement.

A minimal statement is for example
```sql
SELECT INT(val) FROM (VALUES (2147483647), (2147483648) ) t (val)
```

Here the second value exceeds the maximum integer value. 

Executing this in db2 console gives
```
db2 => SELECT INT(val) FROM (VALUES (2147483647), (2147483648) ) t (val)

1
-----------
 2147483647
SQL0413N  Overflow occurred during numeric data type conversion.
SQLSTATE=22003
```

Executing this in DataGrip gives
```
[22003][-413] Overflow occurred during numeric data type conversion.. SQLCODE=-413, SQLSTATE=22003, DRIVER=4.7.85
```

However there is no error when executing that query within a golang program. As a result the program continues to scan. Only those rows before the corrupted row are included in the resulting set. All rows after the corrupted row are missing. Here is a minimal test file.

```ts
package main_test

import (
	"database/sql"
	"log"
	"testing"

	_ "github.com/asifjalil/cli"
)

func TestOverflow(t *testing.T) {
	dbc, err := sql.Open("cli", "DSN=database;UID=user;PWD=password;")
	defer dbc.Close()

	if err != nil {
		t.Error(err)
	}

	// this statement should report an overflow error
	// when casting the second value (2147483648) to an INT
	rows, err := dbc.Query("SELECT INT(val) FROM (VALUES (2147483647), (2147483648), (2147483647) ) t (val)")

	var values []string
	for rows.Next() {
		var value string
		rows.Scan(&value)
		values = append(values, value)
	}

	log.Printf("values: %+v err: %+v", values, err)

	if err != nil {
		// on overflow error we should get here, but we don't
		t.Error(err)
	} else {
		// otherwise we expect 3 values
		if len(values) != 3 {
			t.Errorf("expected 3 values but got %d", len(values))
		}
	}
}
```

**Comment by asifjalil** [comment]
@giniedp Thanks for reporting it and for including test code. I will investigate.

**Comment by asifjalil** [comment]
@giniedp The error happens when the values are fetched using rows.Next(), so we need to check rows.Err(). If you change the test code like this:

```go
for rows.Next() {
    var value string
    rows.Scan(&value)
    values = append(values, value)
}
err = rows.Err()
log.Printf("values: %+v err: %+v", values, err)
```

You should see the following output:

> values: [2147483647] err: database/sql/driver: [IBM][CLI Driver][DB2/LINUXX8664] SQL0413N  Overflow occurred during numeric data type conversion.  SQLSTATE=22003



>

**Comment by giniedp** [comment]
oh, i see. Thank you for looking into it.
