### ISSUE TITLE
ErrBadConn must be returned upon connection related errors

### ISSUE THREAD

**Issue by shrek** [asifjalil/cli#14]
The database/sql package maintains a connection pool, and uses the error ErrBadConn from the driver as a signal that the connection has gone bad.
See: 
https://golang.org/src/database/sql/driver/driver.go
Upon ErrBadConn from the driver, database/sql prunes the connection from the pool and may retry on a new connection. See: https://golang.org/src/database/sql/sql.go

If the driver does not return ErrBadConn, then in the following scenario, the application continuously gets errors from database/sql because, it is reusing the bad/closed connection.

The following simple test demonstrates this:

1) stop the database docker to simulate connection errors
2) restart the database docker.

Now, Even though the database is up, the application continues to get sql errors because of the bad connection which is closed.

PR: https://github.com/asifjalil/cli/pull/13 is a fix to this problem

**Comment by shrek** [comment]
@asifjalil : could you please create a new release, so the users of this library can vendor the latest release ?

**Comment by asifjalil** [comment]
@shrek Done. I just released v1.2.7 that has the fix.
