### ISSUE TITLE
Problem with sqlcode error after migrating to v1.2.8

### ISSUE THREAD

**Issue by eriklupander** [asifjalil/cli#16]
Hi,

thank you for your excellent work.

**Summary**
We're having a bit of a hard time understanding how the latest changes in 1.2.8 affects error handling + that we're getting a strange SQLCode -99999 not seen anywhere.

**Environment**
Go 1.14.4 (Linux)
CLI-driver version: 11.5 (Linux)
DB2 LUW version: 11.5

**Description**
After upgrading your library from v1.2.7 to the 1.2.8 release we've been getting some issues we're having a hard time pinning down.

More specifically, we are now getting errors such as:

`DB2 error with SQLCode -99999: database/sql/driver: [IBM][CLI Driver]  SQLSTATE=01S07[IBM][CLI Driver]  SQLSTATE=01S07` 

This seems to indicate some truncation going on. This happens on a few SELECT statements including selecting TIMESTAMP columns.

While it does make sense that the change on how SQL_SUCCESS_WITH_INFO is handled affects a truncated response, my issue is that the following code reports the SQLCode `-99999` when the error above occurs. Shouldn't SQLCodes for SQL_SUCCESS_WITH_INFO be positive integers?

Our code, derived from the error handling code in your README:
```
type sqlcode interface {
	SQLCode() int
	SQLState() string
}

func checkError(err error) error {

	if err != nil {
		if err2, ok := err.(sqlcode); ok {
			code := err2.SQLCode()
			if code < 0 {
                                 // Handle errors
			        return errors.Wrapf(err, "DB2 error with SQLCode %v", code)
			} else if code == 0 {
                                 // Handle OK (probably no err to handle in the first place so unlikely to ever get here)
				return nil
			} else {
                                 // Handle SQL_SUCCESS_WITH_INFO which should have positive SQLCode
				return nil
			}
		}
	}
	return err
}
```

Can you shed some light on how we should expect the CLI wrapper to work in regard to SQL_SUCCESS_WITH_INFO? My understanding is that a response with `SQL_SUCCESS_WITH_INFO` should make the call to the wrapper return an `error`. However, I guess we should be able to determine whether it's a recoverable (i.e. SQL_SUCCESS_WITH_INFO) error or a "normal" error.

While we certainly can rollback to 1.2.7, we really want to handle/log these warnings so we can mitigate any issues as early as possible.

Again, thank you for your work!

**Comment by asifjalil** [comment]
@eriklupander Do you have [TimestampTruncErrToWarning](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0058997.html) set in db2cli.ini? It seems if you want the truncation as a warning and **TimestampTruncErrToWarning** is set to 1, then Db2 returns SQLSTATE `01S07`. Since IBM specifies this behaviour in Information Center, maybe for queries with timestamps, you can ignore SQLSTATE `01S07` or treat it as a warning?

Thanks.

**Comment by eriklupander** [comment]
@asifjalil  Thank you for your answer. I'm a bit confused about the semantics of SQLSTATE `01S07` since the linked page states that it is the `WARNING` response while `22007` is the `ERROR` one. I imagine a `WARNING` should correspond to `SQL_SUCCESS_WITH_INFO` and have a positive integer as `SQLCode`?

Anyway, I'll continue investigating what I can come up with by changing settings in `db2cli.ini`. Again, thank you very much for your help!

**Comment by eriklupander** [comment]
While we havn't been able to track down all aspects of this problem, it's clear from tracing the CLI driver that the `-99999` SQLCode is something produced by DB2 or the CLI driver rather than a problem in the wrapper. Extract from CLI trace:

```
[06/15/2020 12:22:25.778092]     <--- SQL_SUCCESS_WITH_INFO   Time elapsed - +1.970000E-003 seconds
[06/15/2020 12:22:25.778494] SQLGetDiagRecW( pszSqlState="01S07", pfNativeError=-99999, pszErrorMsg="[IBM][CLI Driver]  SQLSTATE=01S07", pcbErrorMsg=33 )
```

I'm closing this issue. Thank you so much for looking into this.
