### ISSUE TITLE
bad pointer in frame github.com/asifjalil/cli.(*conn).setAutoCommitAttr.func1

### ISSUE THREAD

**Issue by eriklupander** [asifjalil/cli#17]
Hi,

we are getting occasional (rare) panics in the wrapper due to `bad pointer in frame` when a transaction is commited.

**Environment**
Go 1.14.4 (Linux)
asifjalil/cli version: v1.2.7
CLI-driver version: 11.5 (Linux)
DB2 LUW version: 11.5

**Description**
This problem typically occurs after many (6+) hours of lightly load-testing a Go application that uses your CLI driver wrapper. E.g. typically the application works as expected, but suddenly a call to Commit through the database/sql package fails with a `bad pointer in frame` when the wrapper tries to invoke `setAutoCommitAttr` after invoking Commit on the database/sql tx. This causes the application to panic:

```
Jun 15 23:57:06 : runtime: bad pointer in frame github.com/asifjalil/cli.(*conn).setAutoCommitAttr.func1 at 0xc00082f4e0: 0x1
Jun 15 23:57:06 : fatal error: invalid pointer found on stack
Jun 15 23:57:06 : runtime stack:
Jun 15 23:57:06 : runtime.throw(0xcce6f4, 0x1e)
Jun 15 23:57:06 : /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0x7f24aa9fb6c8 sp=0x7f24aa9fb698 pc=0x43f752
Jun 15 23:57:06 : runtime.adjustpointers(0xc00082f4e0, 0x7f24aa9fb7c8, 0x7f24aa9fbb58, 0x12e6818, 0x1529260)
Jun 15 23:57:06 : /usr/local/go/src/runtime/stack.go:599 +0x220 fp=0x7f24aa9fb728 sp=0x7f24aa9fb6c8 pc=0x458770
Jun 15 23:57:06 : runtime.adjustframe(0x7f24aa9fba68, 0x7f24aa9fbb58, 0x1529260)
Jun 15 23:57:06 : /usr/local/go/src/runtime/stack.go:641 +0x34e fp=0x7f24aa9fb7f8 sp=0x7f24aa9fb728 pc=0x458ace
Jun 15 23:57:06 : runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc0002dc900, 0x0, 0x0, 0x7fffffff, 0xcfaac0, 0x7f24aa9fbb58, 0x0, ...)
Jun 15 23:57:06 : /usr/local/go/src/runtime/traceback.go:334 +0x110e fp=0x7f24aa9fbad0 sp=0x7f24aa9fb7f8 pc=0x465fae
Jun 15 23:57:06 : runtime.copystack(0xc0002dc900, 0x10000)
Jun 15 23:57:06 : /usr/local/go/src/runtime/stack.go:888 +0x291 fp=0x7f24aa9fbc88 sp=0x7f24aa9fbad0 pc=0x4591d1
Jun 15 23:57:06 : runtime.shrinkstack(0xc0002dc900)
Jun 15 23:57:06 : /usr/local/go/src/runtime/stack.go:1141 +0x128 fp=0x7f24aa9fbcb0 sp=0x7f24aa9fbc88 pc=0x45a0b8
Jun 15 23:57:06 : runtime.newstack()
Jun 15 23:57:06 : /usr/local/go/src/runtime/stack.go:1017 +0x276 fp=0x7f24aa9fbe40 sp=0x7f24aa9fbcb0 pc=0x459506
Jun 15 23:57:06 : runtime.morestack()
Jun 15 23:57:06 : /usr/local/go/src/runtime/asm_amd64.s:449 +0x8f fp=0x7f24aa9fbe48 sp=0x7f24aa9fbe40 pc=0x47018f
Jun 15 23:57:06 : goroutine 638059 [running]:
Jun 15 23:57:06 : runtime.cgoCheckPointer(0xb89ce0, 0x1, 0x0, 0x0)
Jun 15 23:57:06 : /usr/local/go/src/runtime/cgocall.go:428 +0x1b8 fp=0xc00082f4b8 sp=0xc00082f4b0 pc=0x40e718
Jun 15 23:57:06 : github.com/asifjalil/cli.(*conn).setAutoCommitAttr.func1(0xc000458e20, 0x1, 0xc0005b7520)
Jun 15 23:57:06 : /go/pkg/mod/github.com/asifjalil/cli@v1.2.7/conn.go:222 +0x4f fp=0xc00082f4f8 sp=0xc00082f4b8 pc=0xafc69f
Jun 15 23:57:06 : github.com/asifjalil/cli.(*conn).setAutoCommitAttr(0xc000458e20, 0x1, 0xc000090000, 0xc0000d5480)
Jun 15 23:57:06 : /go/pkg/mod/github.com/asifjalil/cli@v1.2.7/conn.go:222 +0x35 fp=0xc00082f520 sp=0xc00082f4f8 pc=0xaf7095
Jun 15 23:57:06 : github.com/asifjalil/cli.(*conn).endTx(0xc000458e20, 0xc0005b7601, 0xc00026f760, 0xc0002b9e00)
Jun 15 23:57:06 : /go/pkg/mod/github.com/asifjalil/cli@v1.2.7/conn.go:259 +0x77 fp=0xc00082f550 sp=0xc00082f520 pc=0xaf7217
Jun 15 23:57:06 : github.com/asifjalil/cli.(*tx).Commit(0xc0000aca40, 0x0, 0x12)
Jun 15 23:57:06 : /go/pkg/mod/github.com/asifjalil/cli@v1.2.7/tx.go:17 +0x3c fp=0xc00082f580 sp=0xc00082f550 pc=0xafbddc
Jun 15 23:57:06 : database/sql.(*Tx).Commit.func1()
Jun 15 23:57:06 : /usr/local/go/src/database/sql/sql.go:2095 +0x3c fp=0xc00082f5b0 sp=0xc00082f580 pc=0x50bc8c
Jun 15 23:57:06 : database/sql.withLock(0xdfbe20, 0xc0000d5480, 0xc0005b7610)
Jun 15 23:57:06 : /usr/local/go/src/database/sql/sql.go:3184 +0x69 fp=0xc00082f5e0 sp=0xc00082f5b0 pc=0x50ad69
Jun 15 23:57:06 : database/sql.(*Tx).Commit(0xc000217180, 0xc0000f4a20, 0x102)
Jun 15 23:57:06 : /usr/local/go/src/database/sql/sql.go:2094 +0x11b fp=0xc00082f638 sp=0xc00082f5e0 pc=0x5055bb
```

This problem has occurred in different parts of our codebase communicating with the DB, so it is not isolated to a given function in our application.

I understand that troubleshooting this issue can be difficult, especially for something not easily reproducible. But perhaps it is possible there's some CGO / unsafe problem in the wrapper code or that the call to change autocommit happens on a "bad" connection? I've looked at the code in question:

```
func (c *conn) setAutoCommitAttr(a uintptr) error {
	ret := C.SQLSetConnectAttr(C.SQLHDBC(c.hdbc), C.SQL_ATTR_AUTOCOMMIT,
		C.SQLPOINTER(a), C.SQL_IS_UINTEGER) <-- line 222
	if !success(ret) {
		return formatError(C.SQL_HANDLE_STMT, c.hdbc)
	}
	return nil
}
```
but can't find any obvious problem. 

Any thoughts on this?

Thanks!

**Comment by asifjalil** [comment]
@eriklupander Thanks for reporting the issue. I will take a look. 

Thanks.

**Comment by eriklupander** [comment]
@asifjalil We believe that the problem is somehow related to us moving from Go 1.13.7 to 1.14.4. 

We have managed to reproduce the issue about 10 times in three different environments with the application built with Go 1.14.4. Has taken somewhere between 6-20 hours for the crash to occur.

We then rebuilt the application with Go 1.13.7 and have not seen a single crash in 100+ hours in different environments.

While this observation rather strongly indicates the crash being due to a regression or change in Go 1.14.x, my CGO / unsafe skills are not sufficient to conclusively say it's a Go 1.14 bug or if there could be some issue in the wrapper. 

I do know there were some changes to the Go `runtime` package in Go 1.14, especially in regard to `defer` which caused https://github.com/golang/go/issues/37688 to be reported. I can't say whether that could be related to the problem seen here, especially given that it seems to have been fixed in Go 1.14.2 though someone just commented that the issue might have resurfaced in Go 1.14.3.

Perhaps I'll see if I can reproduce the problem with Go 1.14.2.

**Comment by asifjalil** [comment]
@eriklupander please try the latest [commit](https://github.com/asifjalil/cli/commit/2598d7f01fdb79080f4a7837561a9fbe019eda39). According to Go 1.14 -d=checkptr flag, this driver had some unsafe pointer conversion and arithmetics. For example, in ```setAutoCommitAttr```. Maybe that was the problem.

**Comment by asifjalil** [comment]
I am adding some notes as to why we may be getting this error. I am not well-versed in unsafe pointer, so I may not be 100% accurate. 

[-d=checkptr](https://github.com/golang/go/issues/22218) proposal uses this example: 

> During stack growth, pointers that have values between 0 and minLegalPointer will cause a "invalid pointer found on stack" exception to be thrown by the runtime. This suggests that storing these pointers on the stack is not a valid operation, i.e. the following code may cause a runtime exception if the stack happens to grow.
```p := unsafe.Pointer(uintptr(1))```

In ```setAutoCommitAttr```, it seems I made this exact mistake: 

```C.SQLPOINTER(a) <-- a is uintptr```

By rewriting ```setAutoCommitAttr``` and making it pass ```-d=checkptr```, I am hoping we can avoid this random ```bad pointer in frame``` error.

**Comment by eriklupander** [comment]
@asifjalil Thank you investigating this issue, your finding seems promising. I'll make sure to try the latest commit, though it make take a little while given vacation season just starting.

**Comment by eriklupander** [comment]
@asifjalil So far so good, my co-workers have load-tested our application built with Go 1.14.4 + your latest commit for 30+ hours without any crashes. While we probably need some more time to definitely say commit https://github.com/asifjalil/cli/commit/2598d7f01fdb79080f4a7837561a9fbe019eda39 solved the issue, so far it seems very promising.

A new release would be nice! Thanks!

**Comment by asifjalil** [comment]
@eriklupander Awesome. Let me know once you are done testing, and I will create a new release.

**Comment by eriklupander** [comment]
@asifjalil We're now at 72+ hours without a single crash, so it does indeed seem as your fix solved our issue. Awesome, thank you very much for resolving this!
