### ISSUE TITLE
Some suggested fixes

### ISSUE THREAD

**Issue by shrek** [asifjalil/cli#2]
These are some findings from my tests, and some suggested fixes that seem to work (not to say that they are the right fixes). Overall, the driver works well.

1) Empty character strings from the db get represented as a byte-slice with all 0s. so, in the application, a check for equality of the string with "" fails. 

2) Count(*) queries return column type as SQL_DECFLOAT. Handle that.
```
+++ b/column.go
@@ -182,6 +182,9 @@ func (c *column) value() (driver.Value, error) {
        case C.SQL_C_DOUBLE:
                return *((*float64)(p)), nil
        case C.SQL_C_CHAR:
+               if buf[0] == 0 {
+                       return "", nil
+               }
                return buf, nil
        case C.SQL_C_WCHAR:
                if p == nil {
@@ -296,6 +299,9 @@ func newColumn(h C.SQLHSTMT, idx int) (*column, error) {
                col.data = make([]byte, size)
        case C.SQL_XML:
                col.ctype = C.SQL_C_BINARY
+       case C.SQL_DECFLOAT:
+                col.ctype = C.SQL_C_DOUBLE
+                col.data = make([]byte, 34)
                // Size is 0, so can't allocate a byte buffer for SQLBindCol.
                // Check out "Data type length (CLI) table" in DB2 Information Center
```
3) Empty binary field results in a panic, handle that.
```
@@ -191,7 +191,9 @@ func (s *stmt) bindParam(idx int, v driver.Value) error {
                sqltype = C.SQL_BINARY
                b := make([]byte, len(d))
                copy(b, d)
-               buf = unsafe.Pointer(&b[0])
+               if len(b) > 0 {
+                       buf = unsafe.Pointer(&b[0])
+               }
                buflen = C.SQLLEN(len(b))
                plen = &buflen
                size = C.SQLULEN(len(b))
```
4) Please list this library under the sql-drivers here..So application writers can find it.
https://github.com/golang/go/wiki/SQLDrivers
The existing library above is not well maintained it appears.

**Comment by asifjalil** [comment]
@shrek Can you tell me how you get empty character string as a byte slice.  I tried something like this: 

```golang
        var emptyString string
        err = db.QueryRow("SELECT '' FROM sysibm.sysdummy1").Scan(&emptyString)
```
That gives a string.

**Comment by shrek** [comment]
@asifjalil : yea i am unable to reproduce 1) so, please ignore that. 

2) I can reproduce with a count(*) query - the interesting thing here is that some db2 servers return SQL_DECIMAL and some SQL_DECFLOAT as column type for the count(*). I suppose it is best to handle SQL_DECFLOAT anyway.

**Comment by asifjalil** [comment]
@shrek Good catch! I figured out why we are getting byte-slice with 0s for an empty string. 

In _func newColumn(...)_, before getting the data from the database, I allocate a byte slice to store the data. The initial size of the byte slice is the column length.  For example, if a char/varchar column size is 64, then the byte slice is initialized to 64 0s. 

In _func value(...)_, I truncate the byte slice using the length that was returned by SQLBindCol. But I only did that if the length > 0. So I missed the empty string.  I am fixing it now and adding a test for an empty string. I will push the new code to GitHub shortly.

**Comment by shrek** [comment]
@asifjalil : thanks ! can you also please provide fixes for handling SQL_DECFLOAT and the panic on empty binary  ?

**Comment by asifjalil** [comment]
@shrek I uploaded the fixes. It includes fixes for the empty string, DECFLOAT, and panic on an empty binary.  Can you please tell me how you tested the panic on an empty binary? 

Try out the latest code and let me know if you run into any other issue.

**Comment by shrek** [comment]
@asifjalil: I tested the fixes and they work ! Thanks ! 

---
The testcase producing the panic is the execution of the following 2 sql statements:
```
&{0xc42014acd0 65537 CREATE TABLE binaries (ID bigint GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,NAME varchar(64),PASSWORDHASH varbinary(255) , PRIMARY KEY 
(ID)) false false []}

&{0xc42014acd0 65537 SELECT ID FROM FINAL TABLE (INSERT INTO binaries (NAME,PASSWORDHASH) VALUES (?,?)) false false []}
```
The prints above are of the struct stmt in your package .

I will open new issues if I find any during my tests, Thanks for the quick fixes.

**Comment by asifjalil** [comment]
@shrek: FYI. While I was going through your VARBINARY test, I found out that it wasn't possible to bind NULL to a VARBINARY parameter. That's because in bindParam, for all nil, I was using SQL_CHAR data type. I fixed that by using SQLDescribeParam. That way I know the type of the parameter and use that for nil. I also added some additional tests for string and varbinary. 

Thanks.
