### ISSUE TITLE
Compilation under Windows fails

### ISSUE THREAD

**Issue by axelniedenhoff** [asifjalil/cli#3]
When I compile the package under Windows (7, 64 bit), I get numerous errors, all of the type

error: unknown type name '__out_ecount_opt'; did you mean 'SAL__out_ecount_opt'?

(There are some variations on this—in addition to __out_ecount_opt, the compiler also stumbles over __in_ecount_opt and __out_bcount_opt). I am using gcc 7.3 from MSYS2 here, but the result is very similar with TDM-GCC 5.1.

Is there a way to make gcc compatible with the DB2 include files?

**Comment by asifjalil** [comment]
@axelniedenhoff According to this DB2 page, it seems DB2 doesn't support gcc on Windows :-(: 

https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.gs.doc/doc/r0023467.html

Only these compilers seem to be supported:

Intel Proton Compiler for Windows 32-bit applications, Version 13.1
Intel C Compiler Version 16.1
Microsoft Visual C++ 2008, 2010

On your Windows machine, check if you have C:\Program Files\DB2\SQLLIB\samples\cli directory. In that directory, **bldapp.bat** is usually used to build a CLI application. I haven't tried building my driver on Windows yet. I will see if I can figure out how to build it on Windows.

**Comment by asifjalil** [comment]
According to [_golang-nuts_](https://groups.google.com/forum/#!msg/golang-nuts/U1WG-AQ8cxs/HKV9G1v4DwAJ) , **cgo** doesn't work with Microsoft Visual C++ compiler.  According to [DB2 Information Center](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.gs.doc/doc/r0023467.html), DB2 libraries only work with Microsoft Visual C++ compiler. I don't think it is possible to the use this Go driver with DB2 on Windows :-(.
