### ISSUE TITLE
Pass CURRENTSCHEMA to Connection string?

### ISSUE THREAD

**Issue by brandonros** [asifjalil/cli#4]
Any working example of this?

**Comment by asifjalil** [comment]
@brandonros Here is an example of how to pass CURRENT SCHEMA using connection string: 
```
func ExampleCurrentSchema() {
        connStr := "DSN = sample; CurrentSchema = SYSIBM"
        qry := "Select 100 from systables fetch first 1 row only"

        log.Println(strings.Repeat("#", 30))
        log.Println("Shows how to set current schema in the connection string")

        log.Printf("sql.Open(\"cli\",\"%s\")\n", connStr)
        db, err := sql.Open("cli", connStr)
        checkError(err)
        defer db.Close()

        var val int
        err = db.QueryRow(qry).Scan(&val)
        checkError(err)

        log.Printf("Expecting 100, got %v\n", val)
        fmt.Println(val)
        // Output: 100
}

```
This example connects to a database called **SAMPLE** and sets the _current schema_ to **SYSIBM**.

In my driver, the _sql.DB_ connection string gets passed to the cli/odbc function [SQLDriverConnect](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0000584.html). **SQLDriverConnect** accepts all the [cli/odbc configuration keywords](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0007964.html).  In DB2 Information Center, if you search for [CurrentSchema CLI/ODBC configuration keyword](https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0008779.html), you will see that the db2cli.ini keyword for current schema is CurrentSchema = _schema name_. That can be used with the **sql.DB** connection string. 

I am also uploading the example to Github. It will be in **example_test.go** file.  Let me know if you have more question.
