### ISSUE TITLE
Fails to compile statically

### ISSUE THREAD

**Issue by brandonros** [asifjalil/cli#5]
```
brandon@debian:~$ CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static" -ldb2' master.go
# github.com/asifjalil/cli
go/src/github.com/asifjalil/cli/tx.go:4:5: undefined: conn
```

**Comment by brandonros** [comment]
```
package cli

type tx struct {
	c *conn
}
```

**Comment by asifjalil** [comment]
@brandonros Let me check. I will get back to you.

**Comment by asifjalil** [comment]
@brandonros My driver needs cgo. It uses DB2's cli driver, which is written in c/c++.  You will need to use **CGO_ENABLED=1**.  Also, my driver code is in multiple files. You can skip the *_test.go files, but all other *.go files need to be included with the build. For example, the following build command should work:
```
CGO_ENABLED=1 GOOS=linux go build -a -ldflags '-extldflags "-static" -ldb2' driver.go conn.go stmt.go tx.go column.go error.go strutil.go
```

**Comment by brandonros** [comment]
Does this mean this driver can never be compiled statically?

**Comment by asifjalil** [comment]
@brandonros It is possible to compile my driver statically.  If you add the following to **tx.go**, it will fix the _undefined: conn_ error: 
```
/*
#cgo LDFLAGS: -ldb2

#include <sqlcli1.h>
*/

import "C"

type tx struct {
        c *conn
}
```

You can use _CGO_ENABLED=0_. But we also need the **libdb2.a** library from IBM: that's the statically compiled DB2 cli/odbc driver (My driver underneath uses DB2 cli/odbc driver to access a DB2 database). I have DB2 11.1 installed on my machine, and I don't see **libdb2.a** installed.  I only see **libdb2.so**. Without **libdb2.a**, we can't compile my driver statically :-(.

**Comment by brandonros** [comment]
I apologize for my lack of Go wisdom, but it sounds like, CGO_ENABLED=0 *must* be supplied for static binaries, and the `libdb2.a` file must exist... and since it doesn't... static binary is not possible?

**Comment by asifjalil** [comment]
@brandonros You are correct. Based on what I have read so far, it seems _CGO_ENABLED=0_ is needed for a static binary. Otherwise, Go will use dynamic linking. Also, like you said, we need _libdb2.a_ to statically link my Go driver to _DB2's cli/odbc_ driver, and _libdb2.a_ is not provided by **IBM**.  So I have the same conclusion: _static binary is not possible unless IBM makes libdb2.a available_.

**Comment by brandonros** [comment]
Thank you so much for your unbelievable support. I am beyond impressed.

Regards,

Brandon
________________________________

**Comment by asifjalil** [comment]
@brandonros I learned a thing or two from your question, so thank you :-).
