### ISSUE TITLE
where to find sqlcli1.h

### ISSUE THREAD

**Issue by aaronsuns** [asifjalil/cli#9]
where to find sqlcli1.h? some ibm installation package?
```
✔ aaronz:~/go/src/github.com/asifjalil/cli [master|✔]> ./install.sh 
# github.com/asifjalil/cli
./column.go:4:10: fatal error: sqlcli1.h: No such file or directory
 #include <sqlcli1.h>
          ^~~~~~~~~~~
compilation terminated.
✘-2 aaronz:~/go/src/github.com/asifjalil/cli [master|✔]> wget https://raw.githubusercontent.com/GerHobbelt/otl/master/build/sqlcli1.h
--2019-03-05 11:30:03--  https://raw.githubusercontent.com/GerHobbelt/otl/master/build/sqlcli1.h
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.84.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.84.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 90084 (88K) [text/plain]
Saving to: ‘sqlcli1.h’

sqlcli1.h                                                     100%[================================================================================================================================================>]  87,97K  --.-KB/s    in 0,003s  

2019-03-05 11:30:03 (25,8 MB/s) - ‘sqlcli1.h’ saved [90084/90084]

✔ aaronz:~/go/src/github.com/asifjalil/cli [master| …1]> ./install.sh 
# github.com/asifjalil/cli
In file included from ./column.go:4:0:
./sqlcli1.h:12:10: fatal error: windows.h: No such file or directory
 #include <windows.h>
          ^~~~~~~~~~~
compilation terminated.
```

**Comment by asifjalil** [comment]
@aaronsuns, 

Please note that my driver only works on Linux and Mac OS X. It doesn't work on Windows. On Windows, IBM DB2 driver doesn't support gcc but Cgo requires gcc.

If you are using Linux or Mac OS x,  you can try this link: 

[IBM Data Server Client Packages](https://www-01.ibm.com/support/docview.wss?uid=swg24044640)

From that page, download **IBM Data Server Driver Package**.  In that download, there should a _include_ directory. It will have _sqlcli1.h_. 

For example, if you download the 64-bit Linux driver package, then you will end up with a _dsdriver_ directory. In _install.sh_ change DB2DIR to _dsdriver_. Then the compilation should work.

**Comment by firewaternottogther** [comment]
@asifjalil 
 i have  downloaded the 64-bit Linux driver package.but The same error occurred.Please specify the  IBM Data Server Driver Package installation path .

**Comment by asifjalil** [comment]
@firewaternottogther in that download please search for `sqlcli1.h`. It should be under an `include` directory. That's just the header file. We also need the DB2 library, so there should be a `lib` directory also.  Hopefully, both `include` and `lib` are under one parent directory. Using that parent directory and `include` and `lib`, set these two environment variables: 

`export CGO_LDFLAGS=-L${some parent directory}/lib`
`export CGO_CFLAGS=-I${some parent directory}/include`

Once these two variables are set, you can run `go build`.

**Comment by asifjalil** [comment]
@firewaternottogther my mistake. Previous [link](https://www-01.ibm.com/support/docview.wss?uid=swg24044640) only has fixpacks. You will need to use this [clients and drivers](https://www-01.ibm.com/support/docview.wss?uid=swg21385217) page. From that page choose [cli driver](http://www.ibm.com/services/forms/preLogin.do?source=swg-idsoc97). It looks like IBM will ask you to register before you can download. If you have an IBM id, then you will need to use that before you can download. As an example, if you download the **64-bit Linux x86 package**, then you will end up downloading `ibm_data_server_driver_for_odbc_cli_linuxx64_v11.1.tar.gz`. If you unpack it, you will get a directory called `clidriver`.  Set the CGO flags like this: 

`export CGO_LDFLAGS=-L${<some dir>/clidriver}/lib`
`export CGO_CFLAGS=-I${<some dir>/clidriver}/include`

**some dir** is the directory where you unpacked the `cli driver`. Once the `cgo` flags are set, build my **Go Driver** by running `go build`.

Hope that helps.
